# Generated by Django 5.2.7 on 2026-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_publication_signature_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='admin_note',
            field=models.TextField(blank=True, default='', verbose_name='Remarque / commentaire admin'),
        ),
    ]
