# Generated by Django 5.2.7 on 2026-06-13 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document'),
        ),
    ]
